### PR TITLE
[Plugin] Fix next-server import broken by 9.0.6

### LINKED ISSUE #157: doesn't work with latest next@9.0.6
after upgrading ```next```to the latest release, plugin fails to build the package

```$ sls offline
Error: Cannot find module 'next-server/dist/server/config'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
      at Function.Module._load (internal/modules/cjs/loader.js:507:25)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:20:18)
      at Object.<anonymous> (/Users/work-dir/node_modules/serverless-nextjs-plugin/lib/parseNextConfiguration.js:1:24)
      at Module._compile (internal/modules/cjs/loader.js:689:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
      at Module.load (internal/modules/cjs/loader.js:599:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
      at Function.Module._load (internal/modules/cjs/loader.js:530:3)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:20:18)
      at Object.<anonymous> (/Users/work-dir/node_modules/serverless-nextjs-plugin/index.js:4:32)
      at Module._compile (internal/modules/cjs/loader.js:689:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
      at Module.load (internal/modules/cjs/loader.js:599:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
      at Function.Module._load (internal/modules/cjs/loader.js:530:3)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:20:18)
      at plugins.forEach.plugin (/Users/work-dir/node_modules/serverless/lib/classes/PluginManager.js:108:18)
      at Array.forEach (<anonymous>)
      at PluginManager.loadPlugins (/Users/work-dir/node_modules/serverless/lib/classes/PluginManager.js:103:13)
      at PluginManager.loadServicePlugins (/Users/work-dir/node_modules/serverless/lib/classes/PluginManager.js:148:10)
      at PluginManager.loadAllPlugins (/Users/work-dir/node_modules/serverless/lib/classes/PluginManager.js:97:10)
      at pluginManager.loadConfigFile.then.then (/Users/work-dir/node_modules/serverless/lib/Serverless.js:78:35)
      at tryCatcher (/Users/work-dir/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/work-dir/node_modules/bluebird/js/release/promise.js:517:31)
      at Promise._settlePromise (/Users/work-dir/node_modules/bluebird/js/release/promise.js:574:18)
      at Promise._settlePromise0 (/Users/work-dir/node_modules/bluebird/js/release/promise.js:619:10)
      at Promise._settlePromises (/Users/work-dir/node_modules/bluebird/js/release/promise.js:699:18)
      at Promise._fulfill (/Users/work-dir/node_modules/bluebird/js/release/promise.js:643:18)
      at Promise._resolveCallback (/Users/work-dir/node_modules/bluebird/js/release/promise.js:437:57)
      at Promise._settlePromiseFromHandler (/Users/work-dir/node_modules/bluebird/js/release/promise.js:529:17)
      at Promise._settlePromise (/Users/work-dir/node_modules/bluebird/js/release/promise.js:574:18)
      at Promise._settlePromise0 (/Users/work-dir/node_modules/bluebird/js/release/promise.js:619:10)
      at Promise._settlePromises (/Users/work-dir/node_modules/bluebird/js/release/promise.js:699:18)
      at Promise._fulfill (/Users/work-dir/node_modules/bluebird/js/release/promise.js:643:18)
      at PromiseArray._resolve (/Users/work-dir/node_modules/bluebird/js/release/promise_array.js:126:19)
      at PromiseArray._promiseFulfilled (/Users/work-dir/node_modules/bluebird/js/release/promise_array.js:144:14)
      at Promise._settlePromise (/Users/work-dir/node_modules/bluebird/js/release/promise.js:579:26)
      at Promise._settlePromise0 (/Users/work-dir/node_modules/bluebird/js/release/promise.js:619:10)
      at Promise._settlePromises (/Users/work-dir/node_modules/bluebird/js/release/promise.js:699:18)
      at Promise._fulfill (/Users/work-dir/node_modules/bluebird/js/release/promise.js:643:18)
      at Promise._resolveCallback (/Users/work-dir/node_modules/bluebird/js/release/promise.js:437:57)
      at Promise._settlePromiseFromHandler (/Users/work-dir/node_modules/bluebird/js/release/promise.js:529:17)
      at Promise._settlePromise (/Users/work-dir/node_modules/bluebird/js/release/promise.js:574:18)
      at Promise._settlePromise0 (/Users/work-dir/node_modules/bluebird/js/release/promise.js:619:10)
      at Promise._settlePromises (/Users/work-dir/node_modules/bluebird/js/release/promise.js:699:18)
      at Promise._fulfill (/Users/work-dir/node_modules/bluebird/js/release/promise.js:643:18)
      at PropertiesPromiseArray.PromiseArray._resolve (/Users/work-dir/node_modules/bluebird/js/release/promise_array.js:126:19)
      at PropertiesPromiseArray._promiseFulfilled (/Users/work-dir/node_modules/bluebird/js/release/props.js:78:14)
      at Promise._settlePromise (/Users/work-dir/node_modules/bluebird/js/release/promise.js:579:26)
      at Promise._settlePromise0 (/Users/work-dir/node_modules/bluebird/js/release/promise.js:619:10)
      at Promise._settlePromises (/Users/work-dir/node_modules/bluebird/js/release/promise.js:699:18)
      at Promise._fulfill (/Users/work-dir/node_modules/bluebird/js/release/promise.js:643:18)
      at Promise._resolveCallback (/Users/work-dir/node_modules/bluebird/js/release/promise.js:437:57)
      at Promise._settlePromiseFromHandler (/Users/work-dir/node_modules/bluebird/js/release/promise.js:529:17)
      at Promise._settlePromise (/Users/work-dir/node_modules/bluebird/js/release/promise.js:574:18)
      at Promise._settlePromise0 (/Users/work-dir/node_modules/bluebird/js/release/promise.js:619:10)
      at Promise._settlePromises (/Users/work-dir/node_modules/bluebird/js/release/promise.js:695:18)
      at _drainQueueStep (/Users/work-dir/node_modules/bluebird/js/release/async.js:138:12)
      at _drainQueue (/Users/work-dir/node_modules/bluebird/js/release/async.js:131:9)
      at Async._drainQueues (/Users/work-dir/node_modules/bluebird/js/release/async.js:147:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/work-dir/node_modules/bluebird/js/release/async.js:17:14)
      at runCallback (timers.js:693:18)
      at tryOnImmediate (timers.js:664:5)
      at processImmediate (timers.js:646:5)
      at process.topLevelDomainCallback (domain.js:121:23)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.8.0
     Framework Version:         1.52.2
     Plugin Version:            3.0.0
     SDK Version:               2.1.1
```

### PR DESCRIPTION
**Pull request by theJoeBiz**
Fixes #157

### CODE REVIEW

**Comment by danielcondemarin** [comment]
Thank you 🙏 Merging 🚀
